(() => {
  const KEY='aimvault-copy-counts'; let activeFilter='all';
  const $=s=>document.querySelector(s), search=$('#searchInput'), sort=$('#sortSelect'), filters=$('#filters'), all=$('#allGrid'), recent=$('#recentGrid'), copied=$('#copiedGrid'), modal=$('#detailModal'), detail=$('#detailContent'), menu=$('#menuButton'), mobile=$('#mobileNav');
  const counts=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return{}}};
  const count=id=>Number(counts()[id]||0);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const empty=(title,text)=>`<div class="empty-state"><div><div class="empty-icon">□</div><strong>${esc(title)}</strong><p>${esc(text)}</p></div></div>`;
  const image=item=>`<img src="${esc(item.image||'')}" alt="${esc(item.name||'Crosshair')}" loading="lazy" onerror="this.replaceWith(Object.assign(document.createElement('span'),{className:'image-unavailable',textContent:'Image unavailable'}))">`;
  const card=item=>`<article class="crosshair-card"><div class="card-image">${image(item)}</div><div class="card-body"><h3 class="card-title" title="${esc(item.name)}">${esc(item.name)}</h3><div class="tags">${(item.tags||[]).slice(0,5).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div><div class="card-actions"><button class="small-button primary" data-copy="${esc(item.id)}">Copy Code</button><button class="small-button" data-view="${esc(item.id)}">View</button></div></div></article>`;
  function buildFilters(){const tags=[...new Set((CROSSHAIRS||[]).flatMap(x=>x.tags||[]).map(String).filter(Boolean))].sort((a,b)=>a.localeCompare(b));filters.innerHTML=[`<button class="filter-button ${activeFilter==='all'?'active':''}" data-filter="all">All</button>`,...tags.map(t=>`<button class="filter-button ${activeFilter===t.toLowerCase()?'active':''}" data-filter="${esc(t.toLowerCase())}">${esc(t)}</button>`)].join('')}
  function items(){let x=[...(Array.isArray(CROSSHAIRS)?CROSSHAIRS:[])],q=search.value.trim().toLowerCase();if(activeFilter!=='all')x=x.filter(i=>(i.tags||[]).some(t=>String(t).toLowerCase()===activeFilter));if(q)x=x.filter(i=>[i.name,i.id,...(i.tags||[])].join(' ').toLowerCase().includes(q));if(sort.value==='name')x.sort((a,b)=>String(a.name).localeCompare(String(b.name)));if(sort.value==='copied')x.sort((a,b)=>count(b.id)-count(a.id));return x}
  function render(){buildFilters();const x=items();all.innerHTML=x.length?x.map(card).join(''):empty(search.value.trim()||activeFilter!=='all'?'No crosshairs match your search.':'No crosshairs added yet.','Add your first crosshair in crosshairs.js');const r=(CROSSHAIRS||[]).slice(0,4);recent.innerHTML=r.length?r.map(card).join(''):empty('No crosshairs added yet.','Add your first crosshair in crosshairs.js');const c=[...(CROSSHAIRS||[])].filter(i=>count(i.id)>0).sort((a,b)=>count(b.id)-count(a.id)).slice(0,4);copied.innerHTML=c.length?c.map(card).join(''):empty('No crosshairs copied yet.','Copy a crosshair code to see it here.')}
  async function copy(id,btn){const item=(CROSSHAIRS||[]).find(x=>x.id===id);if(!item)return;try{await navigator.clipboard.writeText(item.code||'')}catch{const a=document.createElement('textarea');a.value=item.code||'';document.body.appendChild(a);a.select();document.execCommand('copy');a.remove()}const c=counts();c[id]=Number(c[id]||0)+1;localStorage.setItem(KEY,JSON.stringify(c));const old=btn.textContent;btn.textContent='Copied ✓';setTimeout(()=>btn.textContent=old,1100);render()}
  function view(id){const i=(CROSSHAIRS||[]).find(x=>x.id===id);if(!i)return;detail.innerHTML=`<div class="detail-layout"><div class="detail-image">${image(i)}</div><div class="detail-info"><h2 id="detailTitle">${esc(i.name)}</h2><div class="tags">${(i.tags||[]).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div><div class="code-box">${esc(i.code||'No code added.')}</div><p class="section-note">Local browser copies: ${count(i.id)}</p><button class="button button-primary" data-copy="${esc(i.id)}">Copy Code</button></div></div>`;modal.hidden=false;document.body.style.overflow='hidden'}
  function close(){modal.hidden=true;document.body.style.overflow=''}
  document.addEventListener('click',e=>{const c=e.target.closest('[data-copy]');if(c){copy(c.dataset.copy,c);return}const v=e.target.closest('[data-view]');if(v){view(v.dataset.view);return}const f=e.target.closest('[data-filter]');if(f){activeFilter=f.dataset.filter;render();return}if(e.target.matches('[data-close-modal]'))close();if(e.target.closest('.mobile-nav a')){mobile.classList.remove('open');menu.setAttribute('aria-expanded','false')}});
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.hidden)close()});search.addEventListener('input',render);sort.addEventListener('change',render);menu.addEventListener('click',()=>{const open=mobile.classList.toggle('open');menu.setAttribute('aria-expanded',String(open))});render();
})();
